// src/services/storage/mockInitialData.ts
import { Routine, WorkoutSession, PersonalRecord, UserProfile } from '../../types';

export const initialGuestProfile: UserProfile = {
  id: 'guest-user',
  displayName: 'Athlete',
  isGuest: true,
  weightUnit: 'kg',
  restTimerDefaultSeconds: 90,
  soundEnabled: true,
  createdAt: new Date().toISOString(),
};

export const defaultRoutine: Routine = {
  id: 'routine-ppl',
  name: 'Push Pull Legs (PPL)',
  description: 'Classic sequential bodybuilding split designed for progressive overload and recovery.',
  currentQueueIndex: 0,
  targetDaysPerWeek: 5,
  createdAt: new Date().toISOString(),
  lastCompletedDate: undefined,
  days: [
    {
      id: 'day-push',
      name: 'Push',
      dayOrder: 0,
      estimatedMinutes: 50,
      exercises: [
        {
          id: 'ex-bench',
          name: 'Barbell Bench Press',
          muscleGroup: 'Chest',
          targetSets: 4,
          targetRepsMin: 6,
          targetRepsMax: 10,
          notes: 'Focus on leg drive and controlled eccentric.',
          orderIndex: 0,
        },
        {
          id: 'ex-incline-db',
          name: 'Incline Dumbbell Press',
          muscleGroup: 'Chest',
          targetSets: 3,
          targetRepsMin: 8,
          targetRepsMax: 12,
          notes: '30 degree bench angle.',
          orderIndex: 1,
        },
        {
          id: 'ex-pec-dec',
          name: 'Pec Dec Fly',
          muscleGroup: 'Chest',
          targetSets: 3,
          targetRepsMin: 12,
          targetRepsMax: 15,
          notes: 'Seat position 4. Squeeze at peak contraction.',
          orderIndex: 2,
        },
        {
          id: 'ex-ohp',
          name: 'Dumbbell Shoulder Press',
          muscleGroup: 'Shoulders',
          targetSets: 3,
          targetRepsMin: 8,
          targetRepsMax: 12,
          notes: 'Elbows slightly tucked.',
          orderIndex: 3,
        },
        {
          id: 'ex-lateral-raise',
          name: 'Lateral Raise',
          muscleGroup: 'Shoulders',
          targetSets: 4,
          targetRepsMin: 12,
          targetRepsMax: 15,
          notes: 'Slow negative, lead with elbows.',
          orderIndex: 4,
        },
        {
          id: 'ex-tricep-pushdown',
          name: 'Triceps Pushdown',
          muscleGroup: 'Triceps',
          targetSets: 3,
          targetRepsMin: 10,
          targetRepsMax: 15,
          notes: 'Flare rope out at bottom.',
          orderIndex: 5,
        },
      ],
    },
    {
      id: 'day-pull',
      name: 'Pull',
      dayOrder: 1,
      estimatedMinutes: 50,
      exercises: [
        {
          id: 'ex-lat-pulldown',
          name: 'Lat Pulldown',
          muscleGroup: 'Back',
          targetSets: 4,
          targetRepsMin: 8,
          targetRepsMax: 12,
          notes: 'Pull with elbows down and back.',
          orderIndex: 0,
        },
        {
          id: 'ex-barbell-row',
          name: 'Barbell Bent Over Row',
          muscleGroup: 'Back',
          targetSets: 4,
          targetRepsMin: 8,
          targetRepsMax: 10,
          notes: 'Keep spine neutral.',
          orderIndex: 1,
        },
        {
          id: 'ex-seated-cable-row',
          name: 'Seated Cable Row',
          muscleGroup: 'Back',
          targetSets: 3,
          targetRepsMin: 10,
          targetRepsMax: 12,
          notes: 'Close-grip V-bar.',
          orderIndex: 2,
        },
        {
          id: 'ex-face-pull',
          name: 'Face Pull',
          muscleGroup: 'Shoulders',
          targetSets: 3,
          targetRepsMin: 15,
          targetRepsMax: 20,
          notes: 'External rotation focus.',
          orderIndex: 3,
        },
        {
          id: 'ex-bicep-curl',
          name: 'Incline Dumbbell Curl',
          muscleGroup: 'Biceps',
          targetSets: 3,
          targetRepsMin: 10,
          targetRepsMax: 12,
          notes: 'Full bicep stretch at bottom.',
          orderIndex: 4,
        },
        {
          id: 'ex-hammer-curl',
          name: 'Hammer Curl',
          muscleGroup: 'Biceps',
          targetSets: 3,
          targetRepsMin: 10,
          targetRepsMax: 15,
          notes: 'Target brachialis.',
          orderIndex: 5,
        },
      ],
    },
    {
      id: 'day-legs',
      name: 'Legs',
      dayOrder: 2,
      estimatedMinutes: 55,
      exercises: [
        {
          id: 'ex-squat',
          name: 'Barbell Back Squat',
          muscleGroup: 'Legs',
          targetSets: 4,
          targetRepsMin: 6,
          targetRepsMax: 10,
          notes: 'Break parallel, keep chest up.',
          orderIndex: 0,
        },
        {
          id: 'ex-rdl',
          name: 'Romanian Deadlift',
          muscleGroup: 'Legs',
          targetSets: 3,
          targetRepsMin: 8,
          targetRepsMax: 12,
          notes: 'Hinge at hips, slight knee bend.',
          orderIndex: 1,
        },
        {
          id: 'ex-leg-press',
          name: 'Leg Press',
          muscleGroup: 'Legs',
          targetSets: 3,
          targetRepsMin: 10,
          targetRepsMax: 15,
          notes: 'Feet shoulder-width apart.',
          orderIndex: 2,
        },
        {
          id: 'ex-leg-curl',
          name: 'Lying Leg Curl',
          muscleGroup: 'Legs',
          targetSets: 3,
          targetRepsMin: 12,
          targetRepsMax: 15,
          notes: 'Squeeze hamstrings at top.',
          orderIndex: 3,
        },
        {
          id: 'ex-calf-raise',
          name: 'Standing Calf Raise',
          muscleGroup: 'Legs',
          targetSets: 4,
          targetRepsMin: 15,
          targetRepsMax: 20,
          notes: '2-second pause at bottom stretch.',
          orderIndex: 4,
        },
      ],
    },
  ],
};

// No sample workout history - clean blank slate for user
export const initialHistoricalSessions: WorkoutSession[] = [];

// No sample personal records - clean blank slate for user
export const initialPRs: PersonalRecord[] = [];
